version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    container_name: "server-1"
  client:
    build: ./client
    depends_on:
      - server
    container_name: "client-1"
